import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import MobileHeader from "@/components/MobileHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        <MobileHeader />
        {children}
      </body>
    </html>
  );
}
